import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Input from "../atoms/input";
import Button from "../atoms/button";
import Text from "../atoms/text";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Input width="80%" height="40px" />
        <Button width="80%" height="40px" icon="lol">
          Login
        </Button>
        <Text variant="h3" underline={true}>
          Helo
        </Text>
      </main>
    </div>
  );
};

export default Home;
